# MODEL TRAINING - testing the full approach
saving models in a different folder using pickle, saving them in the dataframe causes xgboost to crash

**DO NOT RUN AGAIN**

In [1]:
#external libraries
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib.colors as clt
import plotly
import plotly.subplots as sb
import plotly.express as px
import plotly.graph_objects as go
import dotenv
import pandas as pd
import scipy.fft as fft
import scipy.signal as sg
import scipy.io as sio
import pickle as pkl
import xgboost as xgb
import time
import uuid

#project library
from spinco import *

#environment variables
dotenv.load_dotenv('lab.env')

#project variables
datapath=os.environ['DATAPATH']
cognipath=datapath+"/COGNITION"
dreamspath=datapath+"/DREAMS"
masspath=datapath+"/MASS"

## experiment id
we'll use it to create a folder at the end of the script

In [2]:
experimentId=str(uuid.uuid4())

## define a fixed samplerate

In [3]:
samplerate=200

## load mass

In [9]:
#annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate,onlySpindlesFilteredN2=True)
annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate)

In [10]:
annotations=annotations[annotations.type=='spindle'].reset_index(drop=True)
len(annotations)

33458

In [11]:
minDuration=0.3
maxDuration=5
annotations=annotations[annotations.duration>minDuration].reset_index(drop=True)
annotations=annotations[annotations.duration<maxDuration].reset_index(drop=True)
len(annotations)

33269

In [12]:
annotations.head()

,type,expert,subjectId,labelerId,startTime,duration,samplerate,stopTime,startInd,stopInd
0,spindle,E1,0001,0001,888.327805,0.640579,200,888.968384,177666,177794
1,spindle,E1,0001,0001,905.758061,0.578094,200,906.336155,181152,181267
2,spindle,E1,0001,0001,917.731574,0.847603,200,918.579177,183546,183716
3,spindle,E1,0001,0001,922.078189,0.878845,200,922.957034,184416,184591
4,spindle,E1,0001,0001,939.055445,0.757767,200,939.813212,187811,187963

In [13]:
signalsMetadata.head()

,subjectId,file,channel,duration,samplerate,isOriginalSamplerate,database
0,0001,MASS_0001.pkl,C3-CLE,28956.0,200,False,MASS
1,0002,MASS_0002.pkl,C3-CLE,35016.0,200,False,MASS
2,0003,MASS_0003.pkl,C3-CLE,36760.0,200,False,MASS
3,0004,MASS_0004.pkl,C3-CLE,28004.0,200,False,MASS
4,0005,MASS_0005.pkl,C3-CLE,31244.0,200,False,MASS

## define a fixed feature selection to use

In [14]:
featureSelection=loadPickle("featureSelection26.pkl")
featureSelection

   window characteristic   bandName  score
0       2  hjortActivity      beta2   69.0
1       1  hjortActivity      sigma   63.0
2       2  hjortActivity      beta1   42.0
3       2  hjortActivity     delta2   41.0
4     1.5     sigmaIndex  broadband   39.0
5       2     sigmaIndex  broadband   39.0
6       2  hjortActivity      theta   38.0
7       2  hjortMobility      beta1   37.0
8       2  hjortActivity      alpha   35.0
9       1     sigmaIndex  broadband   34.0
10      2  hjortMobility      sigma   32.0
11    1.5  hjortActivity      beta2   30.0
12      2  hjortMobility      beta2   29.0
13      2  hjortMobility      alpha   28.0
14    0.5     sigmaIndex  broadband   28.0
15      2  hjortMobility     delta1   28.0
16      2  hjortActivity      sigma   27.0
17      2      petrosian  broadband   27.0
18      2  hjortActivity  broadband   26.0
19    1.5  hjortActivity      sigma   26.0
20    1.5  hjortActivity      alpha   25.0
21    0.5  hjortActivity      alpha   24.0
22      1  hjortActivity      theta   23.0
23    1.5      petrosian  broadband   22.0
24      2  hjortMobility  broadband   22.0
25    1.5  hjortActivity      theta   22.0

## load data split
10 fold CV with 4 subjects for testing

In [15]:
#by now we used fixed CV data splits instead
dataSplits=loadPickle("dataSplits_LOOCV.pkl")
dataSplits

,train,val,test
0,"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## define annotation criteria
we want to test the models in three diferent ways

In [16]:
annotationCriteria=pd.DataFrame({
    'criteriumId':['0001','0002','0003'],
    'criteriumName':['E1','E2','union'],
    'labelerIdList':[['0001'],['0002'],['0001','0002']]
})

In [17]:
annotationCriteria

  criteriumId criteriumName labelerIdList
0        0001            E1        [0001]
1        0002            E2        [0002]
2        0003         union  [0001, 0002]

In [18]:
experimentModels=pd.merge(annotationCriteria,dataSplits,how='cross')

In [19]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019
30,0003,union,"[0001, 0002]","[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
31,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
32,0003,union,"[0001, 0002]","[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
33,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
34,0003,union,"[0001, 0002]","[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
35,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
36,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
37,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
38,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
39,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
40,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
41,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
42,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
43,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
44,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## model fitting

In [20]:
n_jobs=4 # paralelization parameter for xgboost (keep it 8 as maximum)
learning_rate=0.4
subsample=0.6

num_boost_round=60  #number of boosting rounds per model

models=[]
modelIds=[]
valF1s=[]
spindleTimeRates=[]
for index, row in experimentModels.iterrows():
    print('**********************')
    print(str(index+1)+' of '+str(len(experimentModels)))
    #Define annotations criterium
    usedAnnotations=annotations[annotations.labelerId.isin(row.labelerIdList)].reset_index(drop=True)
    #Features
    trainFeatures=loadFeatureMatrix(row.train,featureSelection,signalsMetadata,samplerate,datapath)
    #Labels
    trainLabels=loadLabelsVector(row.train,usedAnnotations,signalsMetadata,samplerate)

    """ # Restrict trainingto N2 --------------------------------------------------------------->
    maskVector=loadN2maskVector(row.train,hypnograms,signalsMetadata,samplerate)
    trainFeatures=trainFeatures[maskVector,:]
    trainLabels=trainLabels[maskVector]
    #<--------------------------------------------------------------------------------------- """   #not in this experiment
    
    #Train the models
    params={
        'n_jobs':n_jobs,
        'learning_rate':learning_rate,
        'subsample':subsample,
        'objective':'binary:logistic'
    }
    trainDMatrix=xgb.DMatrix(data=trainFeatures,label=trainLabels)
    xgb_model = xgb.train(params,trainDMatrix,num_boost_round=num_boost_round)
    spindleTimeRates.append(sum(trainLabels)/len(trainLabels))
    models.append(xgb_model)
    modelIds.append(str(uuid.uuid4()))

**********************
1 of 45
**********************
2 of 45
**********************
3 of 45
**********************
4 of 45
**********************
5 of 45
**********************
6 of 45
**********************
7 of 45
**********************
8 of 45

In [ ]:
experimentModels["modelId"]=modelIds
experimentModels["spindleTimeRate"]=spindleTimeRates

In [ ]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test,modelId,spindleTimeRate
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,8b2ea581-6dec-4094-957e-cc1ceb7234c5,0.018639
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,80181036-469f-4bcf-95a0-68374649133a,0.020055
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,f6cafb09-5e74-4889-a306-e517e28d70fe,0.021075
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,2bf1e17a-c8bb-4166-8453-7fdff2414b10,0.018331
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,0feacbcf-4f37-402e-8fbc-4e48a2520bd4,0.019222
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,29c70696-0202-4feb-bd78-3579052a4865,0.019625
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,768cb7b4-e534-49f7-b9c4-acfa7b401ffe,0.017824
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,e3d50ec6-a2f8-45fc-88f9-9af0621c2050,0.017542
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,d539204f-ac49-4811-9ed0-9b39bc65c8f3,0.015442
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,1fe9ebda-f8d4-46a7-8ec3-1c1477a12af6,0.016460
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,fef1292a-c2f5-4c3e-96c0-b9ec6f60cb96,0.017297
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,17643ba4-cb3b-4cd8-818b-406abeab9cb3,0.017868
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,deda4266-2cea-44e1-93d6-21d866332ca0,0.016504
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,60d7b18b-ed9c-40bb-98ce-5193ad5abe70,0.018626
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,c8a28ce7-7f69-4a97-bfe2-229b91334659,0.022439
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,bf748cb3-0db0-4e08-b725-3f4b82679017,0.055090
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,57897053-2189-42d0-8c44-90c32b067094,0.060029
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,d9715543-4141-4773-83d3-da2830e98685,0.061873
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,dadf35ae-1f3a-43da-8303-5fff33a435c4,0.060346
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,255a0333-5bc4-45dc-aee7-89f4718866a7,0.056983
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,a636bcf2-756a-4080-bb6e-a1f4cd400f46,0.060034
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,5a2de0ee-a55e-4039-aef4-ee73020fbd45,0.054858
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,68afbb00-3c69-45a0-96fb-c8bb1f3682c7,0.050874
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,97cd3944-413e-48a8-a112-61ad4a62d585,0.053403
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,b38c4b53-8f69-4715-8715-2e45fa1bf3c3,0.051788
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,b7970d34-50d5-4c03-ae58-a9eac2936305,0.054295
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,24ae87c7-0321-4379-be41-54e39eebff8f,0.054393
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,549b83e9-f9d6-40a9-8a7a-0d4ca9756e77,0.052233
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,af4945ef-f9e1-4139-8276-6a1afa9a84bd,0.062733
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,877ff07d-f2c9-476a-b02b-31ee609f9141,0.065389
30,0003,union,"[0001, 0002]","[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,7feab6c6-8ccf-4056-b394-5b6d7b96cb7a,0.056933
31,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,aca6fbc5-bdf4-4890-bc15-bd3cc527aa65,0.061753
32,0003,union,"[0001, 0002]","[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,ec017e6c-bd1b-41f7-af84-ed6023617980,0.063653
33,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,abcd606e-c9ec-4194-807e-4a045dcd0e18,0.061551
34,0003,union,"[0001, 0002]","[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,ba039537-8f79-49cf-8ac8-383434059506,0.058867
35,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,496b4ddf-f8cb-4244-89ad-0439681b820b,0.061559
36,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,7daf0b7c-d584-4841-8dd3-6d4cec075655,0.056429
37,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,cf984650-f856-4b2e-9290-4aba38fd6427,0.052594
38,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,8be0a742-8fa8-4f1f-a081-622ff61d7bb5,0.054510
39,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,87814133-dd28-4c87-860b-c4ef8d85801e,0.053111
40,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,3d0715ed-4682-4fa5-9cc7-f167312e833b,0.055680
41,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,1ec0ffd4-9973-4c92-9d68-80bfc2610b4e,0.055874
42,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,85254932-ed56-4105-92cd-63187d464506,0.053601
43,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,4ae8df49-0dfe-4d18-8f0b-e1dfd3285c3e,0.063944
44,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,e3714d66-0198-4ba1-b455-3405e39de414,0.067267

## save results

In [ ]:
#create parent folder
experimentpath=datapath+"/experiments/"+experimentId
os.mkdir(experimentpath)
#save each of the models
for id, model in zip(modelIds,models):
    model.save_model(experimentpath+"/"+id+".json")
#save experiment information
dumpPickle(experimentpath+"/experimentModels.pkl",experimentModels)
dumpPickle(experimentpath+"/featureSelection.pkl",featureSelection)

In [ ]:
#you need to use this in the following parts of the experiment
print(experimentId)

f9bdb803-d62d-4eb1-a3a6-cd124daf73d0