# MODEL TRAINING - N2 ONLY

**DO NOT RUN AGAIN**

In [1]:
#external libraries
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib.colors as clt
import plotly
import plotly.subplots as sb
import plotly.express as px
import plotly.graph_objects as go
import dotenv
import pandas as pd
import scipy.fft as fft
import scipy.signal as sg
import scipy.io as sio
import pickle as pkl
import xgboost as xgb
import time
import uuid

#project library
from spinco import *

#environment variables
dotenv.load_dotenv('lab.env')

#project variables
datapath=os.environ['DATAPATH']
cognipath=datapath+"/COGNITION"
dreamspath=datapath+"/DREAMS"
masspath=datapath+"/MASS"

## experiment id
we'll use it to create a folder at the end of the script

In [2]:
experimentId=str(uuid.uuid4())

## define a fixed samplerate

In [3]:
samplerate=200

## load mass

In [4]:
#annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate,onlySpindlesFilteredN2=True)
annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate)

In [5]:
annotations=annotations[annotations.type=='spindle'].reset_index(drop=True)
len(annotations)

33458

In [6]:
minDuration=0.3
maxDuration=5
annotations=annotations[annotations.duration>minDuration].reset_index(drop=True)
annotations=annotations[annotations.duration<maxDuration].reset_index(drop=True)
len(annotations)

33269

In [7]:
annotations.head()

,type,expert,subjectId,labelerId,startTime,duration,samplerate,stopTime,startInd,stopInd
0,spindle,E1,0001,0001,888.327805,0.640579,200,888.968384,177666,177794
1,spindle,E1,0001,0001,905.758061,0.578094,200,906.336155,181152,181267
2,spindle,E1,0001,0001,917.731574,0.847603,200,918.579177,183546,183716
3,spindle,E1,0001,0001,922.078189,0.878845,200,922.957034,184416,184591
4,spindle,E1,0001,0001,939.055445,0.757767,200,939.813212,187811,187963

In [8]:
signalsMetadata.head()

,subjectId,file,channel,duration,samplerate,isOriginalSamplerate,database
0,0001,MASS_0001.pkl,C3-CLE,28956.0,200,False,MASS
1,0002,MASS_0002.pkl,C3-CLE,35016.0,200,False,MASS
2,0003,MASS_0003.pkl,C3-CLE,36760.0,200,False,MASS
3,0004,MASS_0004.pkl,C3-CLE,28004.0,200,False,MASS
4,0005,MASS_0005.pkl,C3-CLE,31244.0,200,False,MASS

## define a fixed feature selection to use

In [9]:
featureSelection=loadPickle("featureSelection26.pkl")
featureSelection

   window characteristic   bandName  score
0       2  hjortActivity      beta2   69.0
1       1  hjortActivity      sigma   63.0
2       2  hjortActivity      beta1   42.0
3       2  hjortActivity     delta2   41.0
4     1.5     sigmaIndex  broadband   39.0
5       2     sigmaIndex  broadband   39.0
6       2  hjortActivity      theta   38.0
7       2  hjortMobility      beta1   37.0
8       2  hjortActivity      alpha   35.0
9       1     sigmaIndex  broadband   34.0
10      2  hjortMobility      sigma   32.0
11    1.5  hjortActivity      beta2   30.0
12      2  hjortMobility      beta2   29.0
13      2  hjortMobility      alpha   28.0
14    0.5     sigmaIndex  broadband   28.0
15      2  hjortMobility     delta1   28.0
16      2  hjortActivity      sigma   27.0
17      2      petrosian  broadband   27.0
18      2  hjortActivity  broadband   26.0
19    1.5  hjortActivity      sigma   26.0
20    1.5  hjortActivity      alpha   25.0
21    0.5  hjortActivity      alpha   24.0
22      1  hjortActivity      theta   23.0
23    1.5      petrosian  broadband   22.0
24      2  hjortMobility  broadband   22.0
25    1.5  hjortActivity      theta   22.0

## load data split
10 fold CV with 4 subjects for testing

In [10]:
#by now we used fixed CV data splits instead
dataSplits=loadPickle("dataSplits_LOOCV.pkl")
dataSplits

,train,val,test
0,"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## define annotation criteria
we want to test the models in three diferent ways

In [15]:
annotationCriteria=pd.DataFrame({
    'criteriumId':['0001','0002'],
    'criteriumName':['E1','E2'],
    'labelerIdList':[['0001'],['0002']]
})

In [16]:
annotationCriteria

  criteriumId criteriumName labelerIdList
0        0001            E1        [0001]
1        0002            E2        [0002]

In [17]:
experimentModels=pd.merge(annotationCriteria,dataSplits,how='cross')

In [18]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## load hypnograms

In [19]:
stagesAnnotations=pd.read_csv(datapath+"\MASS\stages\stages.csv")
stagesAnnotations['samplerate']=samplerate
stagesAnnotations['subjectId']=stagesAnnotations.apply(
    lambda row: str(row.subjectId).zfill(4),axis=1)
stagesAnnotations['stopTime']=stagesAnnotations.apply(
    lambda row: row.startTime+row.duration , axis=1)
stagesAnnotations['startInd']=stagesAnnotations.apply(
    lambda row: seconds2index(row.startTime,row.samplerate) , axis=1)
stagesAnnotations['stopInd']=stagesAnnotations.apply(
    lambda row: seconds2index(row.stopTime,row.samplerate) , axis=1)
stagesAnnotations.head(5)

hypnograms={}
for ind, row in signalsMetadata.iterrows():
    subjectId=row.subjectId
    thisStages=stagesAnnotations[stagesAnnotations.subjectId==subjectId]
    excerptDimension=int(row.duration*row.samplerate)
    thisHypnogram=np.ones((excerptDimension,))*np.nan
    for ind_stg, row_stg in thisStages.iterrows():
        thisHypnogram[row_stg.startInd:row_stg.stopInd]=row_stg.value
    hypnograms[subjectId]=thisHypnogram

In [22]:
def loadN2maskVector(subjectList,hypnograms):
    mask=np.array([])
    for subject in subjectList:
        mask=np.concatenate((mask,hypnograms[subject]))
    return mask==2

## model fitting

In [23]:
n_jobs=4 # paralelization parameter for xgboost (keep it 8 as maximum)
learning_rate=0.4
subsample=0.6

num_boost_round=60  #number of boosting rounds per model

models=[]
modelIds=[]
valF1s=[]
spindleTimeRates=[]
for index, row in experimentModels.iterrows():
    print('**********************')
    print(str(index+1)+' of '+str(len(experimentModels)))
    #Define annotations criterium
    usedAnnotations=annotations[annotations.labelerId.isin(row.labelerIdList)].reset_index(drop=True)
    #Features
    trainFeatures=loadFeatureMatrix(row.train,featureSelection,signalsMetadata,samplerate,datapath)
    #Labels
    trainLabels=loadLabelsVector(row.train,usedAnnotations,signalsMetadata,samplerate)

    # Restrict trainingto N2 --------------------------------------------------------------->
    maskVector=loadN2maskVector(row.train,hypnograms)
    trainFeatures=trainFeatures[maskVector,:]
    trainLabels=trainLabels[maskVector]
    #<---------------------------------------------------------------------------------------   #not in this experiment
    
    #Train the models
    params={
        'n_jobs':n_jobs,
        'learning_rate':learning_rate,
        'subsample':subsample,
        'objective':'binary:logistic'
    }
    trainDMatrix=xgb.DMatrix(data=trainFeatures,label=trainLabels)
    xgb_model = xgb.train(params,trainDMatrix,num_boost_round=num_boost_round)
    spindleTimeRates.append(sum(trainLabels)/len(trainLabels))
    models.append(xgb_model)
    modelIds.append(str(uuid.uuid4()))

**********************
1 of 30
**********************
2 of 30
**********************
3 of 30
**********************
4 of 30
**********************
5 of 30
**********************
6 of 30
**********************
7 of 30
**********************
8 of 30
**********************
9 of 30
**********************
10 of 30
**********************
11 of 30
**********************
12 of 30
**********************
13 of 30
**********************
14 of 30
**********************
15 of 30
**********************
16 of 30
**********************
17 of 30
**********************
18 of 30
**********************
19 of 30
**********************
20 of 30
**********************
21 of 30
**********************
22 of 30
**********************
23 of 30
**********************
24 of 30
**********************
25 of 30
**********************
26 of 30
**********************
27 of 30
**********************
28 of 30
**********************
29 of 30
**********************
30 of 30

In [24]:
experimentModels["modelId"]=modelIds
experimentModels["spindleTimeRate"]=spindleTimeRates

In [25]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test,modelId,spindleTimeRate
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,aa11eb61-61e6-41e2-94d5-a4833e9b8d9d,0.040017
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,56daf263-9a04-44a8-a967-ed222c84ae8c,0.042790
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,983f3902-7ddc-4ab2-93e7-4da2577f8b4b,0.041762
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,c0eba1b0-cd60-4e9e-ab7f-71131a829c7e,0.037779
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,d7cf3254-9d32-4e20-a23e-3cdcd3107eaa,0.040051
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,4f832318-c477-4835-acd3-7ec40944edd3,0.040469
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,15e578bc-6917-4cef-a16a-bade7c0b0676,0.037982
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,7e1fcff0-30f4-4f29-90d4-f7171b7700cf,0.037858
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,0f783e82-ff7a-4204-9e47-55e534671311,0.032807
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,99bfe384-9dde-485c-8233-eb9370c0bdbf,0.034677
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,63e51dd9-118d-496b-8b4d-c0fd4db3d962,0.035894
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,1665dd00-eb54-47cb-843d-f21453d9790d,0.037717
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,263de413-4128-436e-b8a1-0bb7ad600f90,0.035624
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,d666c68e-f0ca-4f31-b8f4-f0495ee86bc1,0.036962
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,d88629a4-c108-44c5-9c1b-4008bdd78400,0.045797
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,da70868e-1939-4133-b4f2-71300b6bee83,0.121738
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,49d2f380-0f65-4b26-8afb-e47476214746,0.130514
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,4e7405d5-05d0-40c3-b4f6-dd42cbccad80,0.124868
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,42b90166-111c-497c-9a8f-29d643d6bc74,0.127058
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,0f49ca85-a851-4db7-a583-c2ab93b6f3b1,0.122217
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,d55992c1-1e39-4eb6-b32d-a82fa06c5676,0.126767
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,3dbaf52d-698b-45ae-8755-05da02ebd320,0.119014
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,7bb7204d-f47d-4b57-b737-3cf50289225f,0.112898
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,f68c68a0-9948-4284-89e8-d568d6f72bd5,0.116403
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,ecc614a4-1ffb-48ee-bcc9-f14088e73e06,0.111565
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,ab7ee892-605a-428f-9bf7-83e6a47a50a0,0.114219
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,b879caf7-ba5a-43f0-b3fe-4892b6f10c4f,0.117145
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,e7c33554-d6cf-41f7-9551-f917e50db53d,0.116126
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,1067e24d-f591-43f0-85a3-ad7706769ead,0.127342
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,bc741fef-fe6f-42cf-8814-5b2803f3eafb,0.136630

## save results

In [26]:
#create parent folder
experimentpath=datapath+"/experiments/"+experimentId
os.mkdir(experimentpath)
#save each of the models
for id, model in zip(modelIds,models):
    model.save_model(experimentpath+"/"+id+".json")
#save experiment information
dumpPickle(experimentpath+"/experimentModels.pkl",experimentModels)
dumpPickle(experimentpath+"/featureSelection.pkl",featureSelection)

In [27]:
#you need to use this in the following parts of the experiment
print(experimentId)

37aac705-1a78-4277-9685-3e72d2ed14fe