# MODEL TRAINING - testing the full approach
saving models in a different folder using pickle, saving them in the dataframe causes xgboost to crash

**DO NOT RUN AGAIN**

In [2]:
#external libraries
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib.colors as clt
import plotly
import plotly.subplots as sb
import plotly.express as px
import plotly.graph_objects as go
import dotenv
import pandas as pd
import scipy.fft as fft
import scipy.signal as sg
import scipy.io as sio
import pickle as pkl
import xgboost as xgb
import time
import uuid

#project library
from spinco import *

#environment variables
dotenv.load_dotenv('lab.env')

#project variables
datapath=os.environ['DATAPATH']
cognipath=datapath+"/COGNITION"
dreamspath=datapath+"/DREAMS"
masspath=datapath+"/MASS"

## experiment id
we'll use it to create a folder at the end of the script

In [3]:
experimentId=str(uuid.uuid4())

## define a fixed samplerate

In [4]:
samplerate=200

## load mass

In [5]:
#annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate,onlySpindlesFilteredN2=True)
annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate)

In [6]:
annotations=annotations[annotations.type=='spindle'].reset_index(drop=True)
len(annotations)

33458

In [7]:
minDuration=0.3
maxDuration=5
annotations=annotations[annotations.duration>minDuration].reset_index(drop=True)
annotations=annotations[annotations.duration<maxDuration].reset_index(drop=True)
len(annotations)

33269

In [8]:
annotations.head()

,type,expert,subjectId,labelerId,startTime,duration,samplerate,stopTime,startInd,stopInd
0,spindle,E1,0001,0001,888.327805,0.640579,200,888.968384,177666,177794
1,spindle,E1,0001,0001,905.758061,0.578094,200,906.336155,181152,181267
2,spindle,E1,0001,0001,917.731574,0.847603,200,918.579177,183546,183716
3,spindle,E1,0001,0001,922.078189,0.878845,200,922.957034,184416,184591
4,spindle,E1,0001,0001,939.055445,0.757767,200,939.813212,187811,187963

In [9]:
signalsMetadata.head()

,subjectId,file,channel,duration,samplerate,isOriginalSamplerate,database
0,0001,MASS_0001.pkl,C3-CLE,28956.0,200,False,MASS
1,0002,MASS_0002.pkl,C3-CLE,35016.0,200,False,MASS
2,0003,MASS_0003.pkl,C3-CLE,36760.0,200,False,MASS
3,0004,MASS_0004.pkl,C3-CLE,28004.0,200,False,MASS
4,0005,MASS_0005.pkl,C3-CLE,31244.0,200,False,MASS

## define a fixed feature selection to use

In [10]:
featureSelection=loadPickle("featureSelection_250bootstraping_iterations.pkl")
featureSelection

   window   characteristic   bandName  Times_selected
0       2       sigmaIndex  broadband          1000.0
1       2    hjortActivity      sigma          1000.0
2     1.5       sigmaIndex  broadband          1000.0
3       1    hjortActivity      sigma          1000.0
4       1       sigmaIndex  broadband          1000.0
5       2    hjortActivity      beta1          1000.0
6       2    hjortActivity      beta2          1000.0
7     1.5    hjortActivity      sigma           999.0
8       2    hjortMobility      beta1           994.0
9       2    hjortActivity     delta2           986.0
10      2    hjortActivity  broadband           985.0
11      2    hjortMobility      sigma           975.0
12      2    hjortActivity      alpha           971.0
13    1.5    hjortActivity      beta2           918.0
14    0.5       sigmaIndex  broadband           899.0
15      2    hjortMobility      beta2           897.0
16      2    hjortMobility      alpha           893.0
17      2    hjortMobility     delta1           838.0
18    1.5    hjortMobility      beta1           824.0
19    1.5    hjortActivity      beta1           725.0
20      2        petrosian  broadband           715.0
21      1    hjortActivity  broadband           680.0
22      2    hjortActivity      theta           652.0
23    0.5    hjortActivity      sigma           650.0
24      2    hjortMobility      theta           597.0
25    0.5    hjortActivity      alpha           547.0
26    0.5    hjortActivity     delta2           486.0
27      1    hjortActivity      beta1           466.0
28      1    hjortActivity      alpha           389.0
29    1.5    hjortActivity      alpha           383.0
30      2    hjortMobility     delta2           356.0
31      2    hjortActivity     delta1           354.0
32      1    hjortActivity      theta           351.0
33    0.5  hjortComplexity  broadband           335.0
34    1.5    hjortMobility      sigma           275.0
35      1    hjortMobility      beta2           260.0

## load data split
10 fold CV with 4 subjects for testing

In [11]:
#by now we used fixed CV data splits instead
dataSplits=loadPickle("dataSplits_LOOCV.pkl")
dataSplits

,train,val,test
0,"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## define annotation criteria
we want to test the models in three diferent ways

In [12]:
annotationCriteria=pd.DataFrame({
    'criteriumId':['0001','0002','0003'],
    'criteriumName':['E1','E2','union'],
    'labelerIdList':[['0001'],['0002'],['0001','0002']]
})

In [13]:
annotationCriteria

  criteriumId criteriumName labelerIdList
0        0001            E1        [0001]
1        0002            E2        [0002]
2        0003         union  [0001, 0002]

In [14]:
experimentModels=pd.merge(annotationCriteria,dataSplits,how='cross')

In [15]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019
30,0003,union,"[0001, 0002]","[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
31,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
32,0003,union,"[0001, 0002]","[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
33,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
34,0003,union,"[0001, 0002]","[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
35,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
36,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
37,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
38,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
39,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
40,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
41,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
42,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
43,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
44,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## model fitting

In [16]:
n_jobs=4 # paralelization parameter for xgboost (keep it 8 as maximum)
learning_rate=0.4
subsample=0.6

num_boost_round=60  #number of boosting rounds per model

models=[]
modelIds=[]
valF1s=[]
spindleTimeRates=[]
for index, row in experimentModels.iterrows():
    print('**********************')
    print(str(index+1)+' of '+str(len(experimentModels)))
    #Define annotations criterium
    usedAnnotations=annotations[annotations.labelerId.isin(row.labelerIdList)].reset_index(drop=True)
    #Features
    trainFeatures=loadFeatureMatrix(row.train,featureSelection,signalsMetadata,samplerate,datapath)
    #Labels
    trainLabels=loadLabelsVector(row.train,usedAnnotations,signalsMetadata,samplerate)

    """ # Restrict trainingto N2 --------------------------------------------------------------->
    maskVector=loadN2maskVector(row.train,hypnograms,signalsMetadata,samplerate)
    trainFeatures=trainFeatures[maskVector,:]
    trainLabels=trainLabels[maskVector]
    #<--------------------------------------------------------------------------------------- """   #not in this experiment
    
    #Train the models
    params={
        'n_jobs':n_jobs,
        'learning_rate':learning_rate,
        'subsample':subsample,
        'objective':'binary:logistic'
    }
    trainDMatrix=xgb.DMatrix(data=trainFeatures,label=trainLabels)
    xgb_model = xgb.train(params,trainDMatrix,num_boost_round=num_boost_round)
    spindleTimeRates.append(sum(trainLabels)/len(trainLabels))
    models.append(xgb_model)
    modelIds.append(str(uuid.uuid4()))
    del trainFeatures, trainLabels, usedAnnotations, xgb_model, trainDMatrix

**********************
1 of 45
**********************
2 of 45
**********************
3 of 45
**********************
4 of 45
**********************
5 of 45
**********************
6 of 45
**********************
7 of 45
**********************
8 of 45
**********************
9 of 45
**********************
10 of 45
**********************
11 of 45
**********************
12 of 45
**********************
13 of 45
**********************
14 of 45
**********************
15 of 45
**********************
16 of 45
**********************
17 of 45
**********************
18 of 45
**********************
19 of 45
**********************
20 of 45
**********************
21 of 45
**********************
22 of 45
**********************
23 of 45
**********************
24 of 45
**********************
25 of 45
**********************
26 of 45
**********************
27 of 45
**********************
28 of 45
**********************
29 of 45
**********************
30 of 45
**********************
31 of 45
**********************
32 of 45
**********************
33 of 45
**********************
34 of 45
**********************
35 of 45
**********************
36 of 45
**********************
37 of 45
**********************
38 of 45
**********************
39 of 45
**********************
40 of 45
**********************
41 of 45
**********************
42 of 45
**********************
43 of 45
**********************
44 of 45
**********************
45 of 45

In [17]:
experimentModels["modelId"]=modelIds
experimentModels["spindleTimeRate"]=spindleTimeRates

In [18]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test,modelId,spindleTimeRate
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,4ecbf9fd-9ea2-41f6-82ce-b88ac9b32b76,0.018639
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,510c627b-7f5d-47cf-806f-77699d7869bf,0.020055
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,81fc4ed7-34db-485d-8b93-027a1d57313e,0.021075
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,edd43941-9867-4361-a47e-36b0c1e13e96,0.018331
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,f76f3dc0-a712-49f3-842b-590c783bc6ca,0.019222
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,bedbb2e2-c55d-4931-8937-6ff81b1df99a,0.019625
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,d795bc85-43d1-4349-bf03-fe100d40daf9,0.017824
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,02e88dcd-63b9-408e-848d-a849fc2567a1,0.017542
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,a090862a-9778-4431-9c22-e5d33b1a116c,0.015442
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,e7e4df1d-6250-40e8-bf6c-79a6ed4dbdab,0.016460
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,d47997e9-0f93-4c68-8bfe-3d64bd24b612,0.017297
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,eb8f4601-7957-4990-ba3b-c6892c7180c2,0.017868
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,068a1a2c-d011-489a-be3e-8c36cceb0721,0.016504
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,32691b47-eae8-4fd8-906e-315585ba2df6,0.018626
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,4b322b8b-1809-4f6e-ac12-994435d2fc30,0.022439
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,d79e5be1-85d3-472a-a22e-6481f5b1127b,0.056746
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,604deeeb-1744-4dd9-97c3-bda02d1d0d27,0.061232
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,fd829af9-4256-476c-bc47-c5390cafe144,0.063062
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,9fc96fec-cfb6-405e-8f65-e083b96b4243,0.061716
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,e2547620-adc4-4bd4-9296-83d8386b6430,0.058705
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,04b442ab-22b5-48a7-a1c0-072c20a626f0,0.061530
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,0d3a86ae-0c6c-4b2b-a26b-fad23892331c,0.055908
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,caf69e05-ecee-4093-b879-c3f91599d0af,0.052347
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,ed3f6f59-4859-4d08-b747-68d09e29b921,0.054834
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,a3abdc6c-1e79-45d2-90a9-06416c8ffa59,0.053001
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,7004596b-b1ca-4324-8901-a0778774435f,0.055095
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,b53310fe-00ec-479d-9bfa-8f290e751d12,0.055557
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,578d1542-3fb4-47a1-9d2b-58dd25c765ac,0.053827
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,31ed4519-9d74-4339-ac68-efa3f02eff43,0.064234
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,d47ade15-c1f2-4a60-a813-dfa7c35c1cdf,0.067005
30,0003,union,"[0001, 0002]","[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,cee4ae04-78c0-480c-b771-b72d878f07a0,0.058222
31,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,25e07658-15c2-4041-8d9a-1064d9133948,0.062674
32,0003,union,"[0001, 0002]","[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,c1d7834e-6295-4f46-bfa3-4db3173f67e1,0.064574
33,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,303b93bb-b6f2-4f99-9942-ed426c900274,0.062626
34,0003,union,"[0001, 0002]","[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,a816535e-bf64-4b39-8396-7f1c6de84256,0.060214
35,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,cb9eb098-38e6-4bee-9f1b-51c2139e1c31,0.062749
36,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,1d226ad4-978d-4b0d-85b7-d90cf088183e,0.057242
37,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,86c23abf-02eb-4837-a4b8-ddb5ce575663,0.053738
38,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,7394a943-530e-4596-a9d0-5a44bfd7a264,0.055615
39,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,b3cd4052-3cd0-40ad-8c91-0ed9de27204f,0.054077
40,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,5b3eadc0-e098-4a63-994f-2a587dc91f61,0.056330
41,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,65a5be7e-9bd4-4d5c-ae95-ed5d91f99470,0.056786
42,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,c336a3cf-4351-47ed-83f4-45eda3ee364c,0.054840
43,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,762b5c9d-3486-411a-8e7c-7f616e34ac56,0.065145
44,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,28e31074-81c3-4f12-9f03-0eca1d6c7e21,0.068526

## save results

In [19]:
#create parent folder
experimentpath=datapath+"/experiments/"+experimentId
os.mkdir(experimentpath)
#save each of the models
for id, model in zip(modelIds,models):
    model.save_model(experimentpath+"/"+id+".json")
#save experiment information
dumpPickle(experimentpath+"/experimentModels.pkl",experimentModels)
dumpPickle(experimentpath+"/featureSelection.pkl",featureSelection)

In [20]:
#you need to use this in the following parts of the experiment
print(experimentId)

526685ff-765e-4c02-b4aa-23958be9563f