# MODEL TRAINING - testing the full approach
saving models in a different folder using pickle, saving them in the dataframe causes xgboost to crash

**DO NOT RUN AGAIN**

In [46]:
#external libraries
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib.colors as clt
import plotly
import plotly.subplots as sb
import plotly.express as px
import plotly.graph_objects as go
import dotenv
import pandas as pd
import scipy.fft as fft
import scipy.signal as sg
import scipy.io as sio
import pickle as pkl
import xgboost as xgb
import time
import uuid

#project library
from spinco import *

#environment variables
dotenv.load_dotenv('lab.env')

#project variables
datapath=os.environ['DATAPATH']
cognipath=datapath+"/COGNITION"
dreamspath=datapath+"/DREAMS"
masspath=datapath+"/MASS"

## experiment id
we'll use it to create a folder at the end of the script

In [47]:
experimentId=str(uuid.uuid4())

## define a fixed samplerate

In [48]:
samplerate=200

## load mass

In [49]:
#annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate,onlySpindlesFilteredN2=True)
annotations, signalsMetadata = loadMASSSpindles(masspath,forceSamplerate=samplerate)

In [50]:
#check with EDA results (not needed)
print(len(annotations)/33458)

1.3461653416223325

In [51]:
annotations=annotations[annotations.type=='spindle'].reset_index(drop=True)

In [52]:
annotations.head()

,type,expert,subjectId,labelerId,startTime,duration,samplerate,stopTime,startInd,stopInd
0,spindle,E1,0001,0001,888.327805,0.640579,200,888.968384,177666,177794
1,spindle,E1,0001,0001,905.758061,0.578094,200,906.336155,181152,181267
2,spindle,E1,0001,0001,917.731574,0.847603,200,918.579177,183546,183716
3,spindle,E1,0001,0001,922.078189,0.878845,200,922.957034,184416,184591
4,spindle,E1,0001,0001,939.055445,0.757767,200,939.813212,187811,187963

In [53]:
signalsMetadata.head()

,subjectId,file,channel,duration,samplerate,isOriginalSamplerate,database
0,0001,MASS_0001.pkl,C3-CLE,28956.0,200,False,MASS
1,0002,MASS_0002.pkl,C3-CLE,35016.0,200,False,MASS
2,0003,MASS_0003.pkl,C3-CLE,36760.0,200,False,MASS
3,0004,MASS_0004.pkl,C3-CLE,28004.0,200,False,MASS
4,0005,MASS_0005.pkl,C3-CLE,31244.0,200,False,MASS

## define a fixed feature selection to use

In [54]:
featureSelection=loadPickle("EXT_F1_iteration_7.pkl")
featureSelection

     characteristic   bandName  window
21    hjortActivity      sigma     0.5
66        petrosian  broadband     0.5
22    hjortActivity      theta     0.5
79    relativePower      beta1     0.5
29  hjortComplexity      sigma     0.5

## load data split
10 fold CV with 4 subjects for testing

In [55]:
#by now we used fixed CV data splits instead
dataSplits=loadPickle("dataSplits_LOOCV.pkl")
dataSplits

,train,val,test
0,"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## define annotation criteria
we want to test the models in three diferent ways

In [56]:
annotationCriteria=pd.DataFrame({
    'criteriumId':['0001','0002','0003'],
    'criteriumName':['E1','E2','union'],
    'labelerIdList':[['0001'],['0002'],['0001','0002']]
})

In [57]:
annotationCriteria

  criteriumId criteriumName labelerIdList
0        0001            E1        [0001]
1        0002            E2        [0002]
2        0003         union  [0001, 0002]

In [58]:
experimentModels=pd.merge(annotationCriteria,dataSplits,how='cross')

In [59]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019
30,0003,union,"[0001, 0002]","[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001
31,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002
32,0003,union,"[0001, 0002]","[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003
33,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005
34,0003,union,"[0001, 0002]","[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006
35,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007
36,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009
37,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010
38,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011
39,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012
40,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013
41,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014
42,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017
43,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018
44,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019

## model fitting

In [60]:
n_jobs=4 # paralelization parameter for xgboost (keep it 8 as maximum)
learning_rate=0.4
subsample=0.6

num_boost_round=60  #number of boosting rounds per model

models=[]
modelIds=[]
valF1s=[]
spindleTimeRates=[]
for index, row in experimentModels.iterrows():
    print('**********************')
    print(str(index+1)+' of '+str(len(experimentModels)))
    #Define annotations criterium
    usedAnnotations=annotations[annotations.labelerId.isin(row.labelerIdList)].reset_index(drop=True)
    #Features
    trainFeatures=loadFeatureMatrix(row.train,featureSelection,signalsMetadata,samplerate,datapath)
    #Labels
    trainLabels=loadLabelsVector(row.train,usedAnnotations,signalsMetadata,samplerate)

    """ # Restrict trainingto N2 --------------------------------------------------------------->
    maskVector=loadN2maskVector(row.train,hypnograms,signalsMetadata,samplerate)
    trainFeatures=trainFeatures[maskVector,:]
    trainLabels=trainLabels[maskVector]
    #<--------------------------------------------------------------------------------------- """   #not in this experiment
    
    #Train the models
    params={
        'n_jobs':n_jobs,
        'learning_rate':learning_rate,
        'subsample':subsample,
        'objective':'binary:logistic'
    }
    trainDMatrix=xgb.DMatrix(data=trainFeatures,label=trainLabels)
    xgb_model = xgb.train(params,trainDMatrix,num_boost_round=num_boost_round)
    spindleTimeRates.append(sum(trainLabels)/len(trainLabels))
    models.append(xgb_model)
    modelIds.append(str(uuid.uuid4()))

**********************
1 of 45
**********************
2 of 45
**********************
3 of 45
**********************
4 of 45
**********************
5 of 45
**********************
6 of 45
**********************
7 of 45
**********************
8 of 45
**********************
9 of 45
**********************
10 of 45
**********************
11 of 45
**********************
12 of 45
**********************
13 of 45
**********************
14 of 45
**********************
15 of 45
**********************
16 of 45
**********************
17 of 45
**********************
18 of 45
**********************
19 of 45
**********************
20 of 45
**********************
21 of 45
**********************
22 of 45
**********************
23 of 45
**********************
24 of 45
**********************
25 of 45
**********************
26 of 45
**********************
27 of 45
**********************
28 of 45
**********************
29 of 45
**********************
30 of 45
**********************
31 of 45
**********************
32 of 45
**********************
33 of 45
**********************
34 of 45
**********************
35 of 45
**********************
36 of 45
**********************
37 of 45
**********************
38 of 45
**********************
39 of 45
**********************
40 of 45
**********************
41 of 45
**********************
42 of 45
**********************
43 of 45
**********************
44 of 45
**********************
45 of 45

In [61]:
experimentModels["modelId"]=modelIds
experimentModels["spindleTimeRate"]=spindleTimeRates

In [62]:
experimentModels

,criteriumId,criteriumName,labelerIdList,train,val,test,modelId,spindleTimeRate
0,0001,E1,[0001],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,9e4dd9bb-a7d9-4ee8-a762-d656d8308d91,0.018639
1,0001,E1,[0001],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,5e1bcb8a-f879-4f42-ae21-0e1ae715095f,0.020055
2,0001,E1,[0001],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,2ecef3ee-0879-42d7-bcf0-ecfa0e3e601a,0.021075
3,0001,E1,[0001],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,52b0d6a8-7f01-4694-85d4-14ef17a025b9,0.018331
4,0001,E1,[0001],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,32c9793a-2115-4e77-8b6f-e8f71d09cecb,0.019222
5,0001,E1,[0001],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,241d9889-61ff-47f7-97c2-f502ae3dba38,0.019625
6,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,f6a46037-1f32-40b5-a6ff-cd293b0e4203,0.017824
7,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,6cfc1f74-3653-47eb-a166-f59fefa13825,0.017542
8,0001,E1,[0001],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,68c5483d-9072-4478-8a87-a7af3324f690,0.015442
9,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,349fe35c-b749-431d-8e8c-c288b150e998,0.016460
10,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,4babfd03-bb9d-4dd2-a829-ad9de3f05932,0.017297
11,0001,E1,[0001],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,8b17d41d-edbb-461c-87d2-300850772dae,0.017868
12,0001,E1,[0001],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,0363bbae-1f8e-4b17-9c0c-12617bda2825,0.016504
13,0001,E1,[0001],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,3ab00c3d-e088-430b-81c0-65466ec51055,0.018626
14,0001,E1,[0001],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,a223e573-b48d-418b-a3d3-7c7ae2c5dee7,0.022439
15,0002,E2,[0002],"[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,bf958847-77fc-4eab-9c95-7a30ef71f8ee,0.057005
16,0002,E2,[0002],"[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,f733d4b9-1730-40f9-91c2-f0ac2f36367e,0.061438
17,0002,E2,[0002],"[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,b7018fb5-07f6-4ca6-a2ae-9c1646bde5b9,0.063269
18,0002,E2,[0002],"[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,d47802dc-da95-4420-a6f5-a4bb291c9385,0.062012
19,0002,E2,[0002],"[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,556a03bf-82b3-4468-b1ff-c804988a238a,0.058957
20,0002,E2,[0002],"[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,d6976249-69b2-42de-a8b2-16adbd07e4b9,0.061686
21,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,3237920b-4e80-4a7b-83af-d66298816ba3,0.056088
22,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,92756d09-a80a-49f1-bbfc-f8a12570ddbe,0.052646
23,0002,E2,[0002],"[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,2d1def14-06c9-4a40-a577-752522c66ed5,0.055127
24,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,c930c4a8-32c1-41d8-a540-db8ec02d8c50,0.053302
25,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,6907442d-1a9b-43cd-9fe4-9121ddc99243,0.055264
26,0002,E2,[0002],"[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,b76944b2-6421-4f77-a082-43f348cd7e7c,0.055852
27,0002,E2,[0002],"[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,ca57f68a-6762-4170-9f27-043a81703239,0.054126
28,0002,E2,[0002],"[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,657f22e6-d58c-4ebd-b837-9ffa0b1aa3a7,0.064451
29,0002,E2,[0002],"[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,f07a4cf8-c75c-4087-9b66-b678bcf1c5d8,0.067263
30,0003,union,"[0001, 0002]","[0003, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0017, 0002, 0006]",0001,f3ec491b-0006-4caa-ae15-ae896cb2d67e,0.058468
31,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0007, 0009, 0010, 0011, 001...","[0006, 0013, 0019]",0002,6491a608-d9e0-4af8-bfcb-4213b7921942,0.062867
32,0003,union,"[0001, 0002]","[0002, 0005, 0007, 0009, 0010, 0011, 0012, 001...","[0013, 0006, 0001]",0003,257f50f6-47f8-43cb-bd89-084609bb54f4,0.064768
33,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0006, 0007, 0009, 0010, 001...","[0018, 0014, 0012]",0005,1531e4ee-35ce-4d1c-a1f9-c3c93a7adb13,0.062913
34,0003,union,"[0001, 0002]","[0003, 0007, 0009, 0010, 0011, 0012, 0013, 001...","[0005, 0001, 0002]",0006,ea67e468-eb31-4b91-9973-01efd704fdfd,0.060454
35,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0010, 0011, 0012, 0013, 001...","[0005, 0006, 0009]",0007,36af1678-f8a9-4522-bf98-7726af8393a9,0.062901
36,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0002, 0017, 0013]",0009,da8325b6-379e-496f-acb8-3c105a943c56,0.057417
37,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0012, 001...","[0017, 0001, 0011]",0010,a832e8e9-3213-4caf-b34f-cdd51a27167b,0.054024
38,0003,union,"[0001, 0002]","[0001, 0003, 0005, 0006, 0009, 0010, 0012, 001...","[0002, 0018, 0007]",0011,8e0df4bf-4d23-4aa8-aa60-b26ac4bc4dbf,0.055899
39,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0009, 0011, 0013, 001...","[0001, 0007, 0010]",0012,a4b03b48-4c81-4340-b92a-12f602f553a2,0.054366
40,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0010, 0011, 001...","[0009, 0001, 0012]",0013,36e2b73b-50a2-4f5b-a897-2d47546b9d67,0.056493
41,0003,union,"[0001, 0002]","[0001, 0002, 0003, 0005, 0006, 0007, 0009, 001...","[0010, 0012, 0011]",0014,4c85ce88-cb17-4ddb-b740-096dc6a82d9d,0.057068
42,0003,union,"[0001, 0002]","[0002, 0003, 0005, 0006, 0007, 0009, 0011, 001...","[0010, 0018, 0001]",0017,190d11b0-5ffe-4468-bceb-b8eb940b8f68,0.055129
43,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0006, 0007, 0010, 0011, 001...","[0012, 0003, 0009]",0018,7966aa35-e638-45df-bea9-250c33a3ca62,0.065360
44,0003,union,"[0001, 0002]","[0001, 0002, 0005, 0007, 0009, 0010, 0011, 001...","[0014, 0006, 0003]",0019,6d036104-a9ed-4fe7-9d7c-14f319e9d0d8,0.068772

## save results

In [63]:
#create parent folder
experimentpath=datapath+"/experiments/"+experimentId
os.mkdir(experimentpath)
#save each of the models
for id, model in zip(modelIds,models):
    model.save_model(experimentpath+"/"+id+".json")
#save experiment information
dumpPickle(experimentpath+"/experimentModels.pkl",experimentModels)
dumpPickle(experimentpath+"/featureSelection.pkl",featureSelection)

In [64]:
#you need to use this in the following parts of the experiment
print(experimentId)

6e8f728f-81ce-4048-8acf-f8d1ffc89a39